### ISSUE TITLE
Create a docker image for this project or a docker-compose config

### ISSUE THREAD

**Issue by geekpete** [shirosaidev/diskover-web#6] opened 2018-05-30 00:40 UTC
Cool project!

A docker image would allow people to spin this up quickly.
A docker-compose config would also allow separate containers for each role, eg nginx vs elasticsearch.
You could use the official Elastic image for the Elasticsearch too.

**Comment by rapphil** [comment] 2018-06-06 04:22
I created an PR addressing your suggestions. Please take a look.
https://github.com/shirosaidev/diskover-web/pull/8

**Comment by geekpete** [comment] 2018-06-08 01:03
So I tried this out, it spins up the containers ok and the web ui can see into the Elasticsearch container just fine to show a list of indices. I've not used Diskover before, so unsure if I'm doing something wrong along the way, but I wasn't able to log into the UI after picking the index to browse.

Do I need to wait for at least one successful processing run to complete first or should it allow logging in while a dir is still being crawled?

**Comment by shirosaidev** [comment] 2018-06-08 03:09
I think the issue is in the Dockerfile there is a CMD to create a symlink
for index.php, it's pointing to selectindices.php, it should be pointing to
dashboard.php.
In diskover-web, you can view indices which the crawls are still running as
well as finished indices.

**Comment by geekpete** [comment] 2018-06-08 03:19
Ok cool, I'll test again when I can and provide outcome.

**Comment by rapphil** [comment] 2018-06-09 23:02
I fixed the issues described by @shirosaidev. I tested and it should work now. 

You need to at least start a crawling using diskover to use the ui.

**Comment by shirosaidev** [comment] 2018-06-15 07:19
I've merged the docker additions into master, thanks!

**Closed as completed** 2018-06-29 10:11 UTC
